#CRISP-DM

1. Compreensão do Negócio: Definir os objetivos do projeto e os requisitos do
ponto de vista do negócio.

2. Compreensão dos Dados: Coletar e explorar os dados para entender sua estrutura e qualidade, identificando quais variáveis são relevantes.

3. Preparação dos Dados: Selecionar, limpar e transformar os dados brutos em um formato adequado para a modelagem. Esta fase pode consumir até 60% do tempo do projeto.

4. Modelagem: Selecionar e aplicar as técnicas de modelagem apropriadas para analisar os dados e encontrar padrões.

5. Avaliação: Avaliar os modelos construídos para verificar se eles atendem aos objetivos definidos na fase de compreensão do negócio e se são eficazes.

6. Implementação: Implantar o modelo final em produção, seja através de relatórios, dashboards ou outras aplicações, para que ele possa gerar valor de forma contínua.

In [ ]:
import pandas as pd

In [ ]:
df_vendas = pd.read_csv('../data-scripts/2/base_vendas.csv')

In [ ]:
# .head(x) - padrão mostra as primeiras x linhas
df_vendas.head(3)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55

In [ ]:
# .tail(x) - padrão mostra as últimas x linhas
df_vendas.tail(3)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [ ]:
# mostra em dataFrames pequenos todas as linhas
# Dataframes grandes mostra as 5 primeiras e as 5 últimas
display(df_vendas)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [ ]:
# visão geral da base de dados (é possível observar que algumas colunas estão com o tipo incorreto e existem linhas nulas na comissão)
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   object
 13  dt_entrega             3000 non-null   object
dtypes: int64(3), object(11)
memory usage: 328.3+ KB

In [ ]:
# (linhas, colunas)
df_vendas.shape

(3000, 14)

In [ ]:
# utilidades para dados numéricos, nem sempre tudo pode ser aproveitado
df_vendas.describe().round(2)

       matricula_funcionario  codigo_produto  quantidade
count           3.000000e+03         3000.00     3000.00
mean            1.234567e+08        10010.47        2.45
std             3.490000e+02            5.77        1.11
min             1.234561e+08        10001.00        1.00
25%             1.234563e+08        10006.00        1.00
50%             1.234567e+08        10011.00        2.00
75%             1.234570e+08        10015.00        3.00
max             1.234571e+08        10020.00        4.00

In [ ]:
# incluindo dados não numéricos (strings, datetime)
df_vendas.describe(include='object')

,Nome Funcionario,Cargo,codigo_loja,nome_loja,descricao_produto,Categoria,preco_custo,valor_unitario,comissao,dt_venda,dt_entrega
count,3000,3000,3000,3000,3000,3000,3000,3000,159,3000,3000
unique,12,1,4,4,20,4,20,19,4,2994,2989
top,José Maria,Vendedor,CL001,Loja Matriz,Aspirador de pó,Casa,"88,9","189,9","0,05",09/07/2019 16:05,09/12/2019 10:12
freq,280,3000,793,793,173,907,173,316,49,2,2

In [ ]:
# quantidade de linhas duplicadas
df_vendas.duplicated().sum()

np.int64(0)

In [ ]:
# quantidade de linhas com informações nulas de cada coluna
# df_vendas.isnull().sum() mesma coisa
df_vendas.isna().sum()

matricula_funcionario       0
Nome Funcionario            0
Cargo                       0
codigo_loja                 0
nome_loja                   0
codigo_produto              0
descricao_produto           0
Categoria                   0
preco_custo                 0
valor_unitario              0
quantidade                  0
comissao                 2841
dt_venda                    0
dt_entrega                  0
dtype: int64

In [ ]:
# instâncias distintas das colunas
df_vendas.nunique()

matricula_funcionario      12
Nome Funcionario           12
Cargo                       1
codigo_loja                 4
nome_loja                   4
codigo_produto             20
descricao_produto          20
Categoria                   4
preco_custo                20
valor_unitario             19
quantidade                  4
comissao                    4
dt_venda                 2994
dt_entrega               2989
dtype: int64

In [ ]:
# instâncias distintas da coluna especificada
df_vendas.nome_loja.unique()

array(['Loja Matriz', 'Filial MG', 'Filial SP', 'Filial ES'], dtype=object)

In [ ]:
# outra forma
df_vendas['Nome Funcionario'].unique()

array(['José Maria', 'Maria das Graças', 'Jorge Mateus', 'Marta Cury',
       'Ricardo Lemos', 'Reginaldo Sodré', 'Felipe Marinho',
       'Marcos Coelho', 'Rita Sampaio', 'Mário Henrique', 'Pamela Lima',
       'Victor Hugo'], dtype=object)

In [ ]:
# nomes de todas as colunas
df_vendas.columns

Index(['matricula_funcionario', 'Nome Funcionario', 'Cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'Categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

##Exercício

In [ ]:
# base airbnb
df_bnb = pd.read_csv('../data-scripts/2/listings.csv')
display(df_bnb)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,17878,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",68997,Matthias,NaN,Copacabana,-22.965990,-43.179400,Entire home/apt,254.0,5,338,2025-06-25,1.86,1,225,19,NaN
1,25026,Beautiful Modern Decorated Studio in Copacabana,102840,Viviane,NaN,Copacabana,-22.976490,-43.191220,Entire home/apt,252.0,2,313,2025-06-23,1.71,1,193,23,NaN
2,35764,COPACABANA SEA BREEZE - RIO - 25 X Superhost,153691,Patricia Miranda & Paulo,NaN,Copacabana,-22.981070,-43.191360,Entire home/apt,190.0,3,516,2025-06-05,2.88,1,103,41,NaN
3,48305,Bright 6bed Penthouse Seconds from Beach,70933,Goitaca,NaN,Ipanema,-22.985910,-43.203020,Entire home/apt,2239.0,7,183,2025-02-25,1.05,6,351,5,NaN
4,48901,Extra large 4BD 3BT on the AtlanticAve. Copaca...,222884,Marcio,NaN,Copacabana,-22.965740,-43.175140,Entire home/apt,743.0,3,48,2025-06-13,0.40,1,311,17,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42567,1450108622211032237,Aconchego Constante,703072927,Marco,NaN,Copacabana,-22.974055,-43.189129,Entire home/apt,186.0,2,0,NaN,NaN,1,137,0,NaN
42568,1450108828266063076,Quarto casal,320682549,Anna,NaN,Camorim,-22.979640,-43.423380,Private room,288.0,1,0,NaN,NaN,1,365,0,NaN
42569,1450124185987579534,Cama em Dorm Misto (9) com AC,37776540,Mariana,NaN,Ipanema,-22.983102,-43.208741,Shared room,87.0,1,0,NaN,NaN,8,213,0,NaN
42570,1450124362124784419,Quarto para casal,378959794,Anna,NaN,Camorim,-22.984526,-43.431740,Private room,240.0,1,0,NaN,NaN,1,365,0,NaN
42571,1450147164497105593,Loft mar-Recreio RJ,697255112,Flavia,NaN,Recreio dos Bandeirantes,-23.023744,-43.458676,Entire home/apt,247.0,1,0,NaN,NaN,5,364,0,NaN

In [ ]:
df_bnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42572 entries, 0 to 42571
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              42572 non-null  int64
 1   name                            42572 non-null  object
 2   host_id                         42572 non-null  int64
 3   host_name                       41092 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   42572 non-null  object
 6   latitude                        42572 non-null  float64
 7   longitude                       42572 non-null  float64
 8   room_type                       42572 non-null  object
 9   price                           38992 non-null  float64
 10  minimum_nights                  42572 non-null  int64
 11  number_of_reviews               42572 non-null  int64
 12  last_review                     33949 non-null  object
 13  reviews_per_month               33949 non-null  float64
 14  calculated_host_listings_count  42572 non-null  int64
 15  availability_365                42572 non-null  int64
 16  number_of_reviews_ltm           42572 non-null  int64
 17  license                         0 non-null      float64
dtypes: float64(6), int64(7), object(5)
memory usage: 5.8+ MB

In [ ]:
df_bnb.describe(include='object')

,name,host_name,neighbourhood,room_type,last_review
count,42572,41092,42572,42572,33949
unique,40290,7058,154,4,1419
top,Apartamento em Copacabana,Daniel,Copacabana,Entire home/apt,2025-06-22
freq,174,431,13099,33990,2685

In [ ]:
df_bnb.describe().round(2)

,id,host_id,neighbourhood_group,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
count,4.257200e+04,4.257200e+04,0.0,42572.00,42572.00,38992.00,42572.00,42572.00,33949.00,42572.00,42572.00,42572.00,0.0
mean,7.837189e+17,2.315791e+08,NaN,-22.97,-43.25,688.01,3.64,25.12,1.20,9.64,199.26,8.89,NaN
std,5.521959e+17,2.152555e+08,NaN,0.04,0.10,3758.45,14.80,47.33,1.27,25.66,126.36,13.09,NaN
min,1.787800e+04,3.607000e+03,NaN,-23.07,-43.72,34.00,1.00,0.00,0.01,1.00,0.00,0.00,NaN
25%,4.786936e+07,3.656636e+07,NaN,-22.98,-43.30,200.00,1.00,1.00,0.28,1.00,88.00,0.00,NaN
50%,9.993601e+17,1.550753e+08,NaN,-22.97,-43.19,311.00,2.00,7.00,0.78,2.00,182.00,3.00,NaN
75%,1.284331e+18,4.253404e+08,NaN,-22.95,-43.18,558.00,3.00,28.00,1.74,5.00,338.00,13.00,NaN
max,1.450245e+18,7.030729e+08,NaN,-22.75,-43.10,500000.00,1000.00,744.00,15.39,226.00,365.00,165.00,NaN

In [ ]:
df_bnb.isna().sum()

id                                    0
name                                  0
host_id                               0
host_name                          1480
neighbourhood_group               42572
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                              3580
minimum_nights                        0
number_of_reviews                     0
last_review                        8623
reviews_per_month                  8623
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
license                           42572
dtype: int64

In [ ]:
df_bnb.nunique()

id                                42572
name                              40290
host_id                           24935
host_name                          7058
neighbourhood_group                   0
neighbourhood                       154
latitude                          26063
longitude                         27444
room_type                             4
price                              2434
minimum_nights                       69
number_of_reviews                   425
last_review                        1419
reviews_per_month                   766
calculated_host_listings_count       66
availability_365                    366
number_of_reviews_ltm               113
license                               0
dtype: int64

In [ ]:
df_bnb.duplicated().sum()

np.int64(0)

In [ ]:
df_bnb.host_name.unique()

array(['Matthias', 'Viviane', 'Patricia Miranda & Paulo', ...,
       'Joel Messias', 'Erika Aparecida', 'Adriano Marques De Souza'],
      dtype=object)

In [ ]:
df_bnb['neighbourhood'].unique()

array(['Copacabana', 'Ipanema', 'Barra da Tijuca', 'Joá', 'Santa Teresa',
       'Gávea', 'Leblon', 'Jacarepaguá', 'Botafogo',
       'Recreio dos Bandeirantes', 'Itanhangá', 'Praça Seca',
       'Laranjeiras', 'Lagoa', 'Humaitá', 'Vidigal', 'Centro',
       'Jardim Botânico', 'Tijuca', 'Flamengo', 'São Conrado', 'Urca',
       'Leme', 'Vila da Penha', 'Glória', 'Vargem Pequena',
       'Alto da Boa Vista', 'Cosme Velho', 'Rocinha', 'Vargem Grande',
       'Penha Circular', 'Estácio', 'Bangu', 'Praça da Bandeira',
       'Taquara', 'Bonsucesso', 'Gamboa', 'Barra de Guaratiba',
       'Rio Comprido', 'Catete', 'Maracanã', 'Engenho Novo', 'Curicica',
       'Vila Isabel', 'Piedade', 'São Francisco Xavier', 'Cachambi',
       'Guaratiba', 'Portuguesa', 'Cavalcanti', 'Grajaú', 'Higienópolis',
       'Anil', 'Rocha Miranda', 'Camorim', 'Freguesia (Jacarepaguá)',
       'São Cristóvão', 'Riachuelo', 'Todos os Santos', 'Campo Grande',
       'Pilares', 'Gardênia Azul', 'Cidade Nova', 'Andaraí', 'Penha',
       'Quintino Bocaiúva', 'Inhoaíba', 'Inhaúma', 'Tauá', 'Gericinó',
       'Pechincha', 'Marechal Hermes', 'Brás de Pina', 'Del Castilho',
       'Sampaio', 'Engenho de Dentro', 'Santíssimo',
       'Ricardo de Albuquerque', 'Rocha', 'Campinho', 'Jardim Guanabara',
       'Méier', 'Abolição', 'Realengo', 'Lins de Vasconcelos',
       'Vila Valqueire', 'Paquetá', 'Anchieta', 'Moneró', 'Encantado',
       'Guadalupe', 'Ramos', 'Cidade de Deus', 'Parque Anchieta',
       'Vasco da Gama', 'Pedra de Guaratiba', 'Bento Ribeiro',
       'Osvaldo Cruz', 'Tanque', 'Vaz Lobo', 'Irajá', 'Água Santa',
       'Cocotá', 'Sepetiba', 'Jardim Sulacap', 'Zumbi', 'Santa Cruz',
       'Vicente de Carvalho', 'Praia da Bandeira', 'Engenho da Rainha',
       'Vigário Geral', 'Santo Cristo', 'Cascadura', 'Jardim Carioca',
       'Grumari', 'Senador Vasconcelos', 'Cacuia', 'Cordovil',
       'Paciência', 'Coelho Neto', 'Vila Kosmos', 'Honório Gurgel',
       'Benfica', 'Cosmos', 'Senador Camará', 'Vila Militar',
       'Parada de Lucas', 'Catumbi', 'Deodoro', 'Bancários', 'Saúde',
       'Pitangueiras', 'Jacaré', 'Olaria', 'Maria da Graça',
       'Jardim América', 'Madureira', 'Padre Miguel', 'Turiaçú',
       'Barros Filho', 'Freguesia (Ilha)', 'Ribeira', 'Pavuna',
       'Engenheiro Leal', 'Tomás Coelho', 'Maré', 'Colégio', 'Mangueira',
       'Complexo do Alemão', 'Galeão', 'Manguinhos',
       'Cidade Universitária', 'Magalhães Bastos', 'Caju'], dtype=object)

In [ ]:
df_bnb.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

In [ ]:
# base titanic
df_titanic = pd.read_csv('../data-scripts/2/Titanic Dataset.csv', sep=';')
display(df_titanic)

,Classe,Sobreviveu,Nome,Sexo,Idade,Irmaos_Conjuges,Pais_Filhos,Bilhete,Tarifa,Cabine,Porto_Embarque,Bote_SalvaVidas,ID_Corpo,Origem_Destino
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,2.113.375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,1.515.500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,1.515.500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,1.515.500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,1.515.500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,144.542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,144.542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,72.250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,72.250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,78.750,NaN,S,NaN,NaN,NaN

In [ ]:
df_titanic.describe()

,Classe,Sobreviveu,Idade,Irmaos_Conjuges,Pais_Filhos,ID_Corpo
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,121.000000
mean,2.294882,0.381971,29.881138,0.498854,0.385027,160.809917
std,0.837836,0.486055,14.413493,1.041658,0.865560,97.696922
min,1.000000,0.000000,0.170000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,328.000000

In [ ]:
df_titanic['Sobreviveu'].sum()

np.int64(500)

In [ ]:
df_titanic.nunique()

Classe                3
Sobreviveu            2
Nome               1307
Sexo                  2
Idade                98
Irmaos_Conjuges       7
Pais_Filhos           8
Bilhete             929
Tarifa              281
Cabine              186
Porto_Embarque        3
Bote_SalvaVidas      27
ID_Corpo            121
Origem_Destino      369
dtype: int64