In [1]:
import pandas as pd

In [2]:
# carregando DataFrame corrigindo o tipo das colunas dt_venda e dt_entrega em datetime, lendo primeiro o dia na conversão
df_vendas = pd.read_csv('../data-scripts/3/base_vendas.csv', parse_dates=['dt_venda', 'dt_entrega'], dayfirst=True)
df_vendas.head()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",2019-08-14 16:56:00,2019-08-19 15:52:00

In [3]:
colunas = df_vendas.columns
print(colunas)

Index(['matricula_funcionario', 'Nome Funcionario', 'Cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'Categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='str')

In [4]:
# padronizando o nome das colunas, letra minúscula e espaço substituído por underline
colunas = list(i.strip().replace(' ', '_').lower() for i in colunas)

In [5]:
df_vendas.columns = colunas

In [6]:
# verificando se a mudança foi bem-sucedida
df_vendas.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",2019-08-14 16:56:00,2019-08-19 15:52:00

In [7]:
# mudando o separador decimal do preço de vírgula para ponto, comum no Brasil
df_vendas['valor_unitario'] = df_vendas['valor_unitario'].str.replace(',', '.')

In [8]:
# convertendo as linhas de string para float
df_vendas['valor_unitario'] = df_vendas['valor_unitario'].astype(float)

In [9]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   nome_funcionario       3000 non-null   str
 2   cargo                  3000 non-null   str
 3   codigo_loja            3000 non-null   str
 4   nome_loja              3000 non-null   str
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   str
 7   categoria              3000 non-null   str
 8   preco_custo            3000 non-null   str
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    str
 12  dt_venda               3000 non-null   datetime64[us]
 13  dt_entrega             3000 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(1), int64(3), str(8)
memory usage: 508.6 KB

In [10]:
df_vendas['preco_custo'] = df_vendas['preco_custo'].str.replace(',', '.')

In [11]:
df_vendas['preco_custo'] = df_vendas['preco_custo'].astype(float)

In [12]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   nome_funcionario       3000 non-null   str
 2   cargo                  3000 non-null   str
 3   codigo_loja            3000 non-null   str
 4   nome_loja              3000 non-null   str
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   str
 7   categoria              3000 non-null   str
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    str
 12  dt_venda               3000 non-null   datetime64[us]
 13  dt_entrega             3000 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(2), int64(3), str(7)
memory usage: 495.2 KB

In [13]:
# forma prática de converter mais de uma coluna
df_vendas = df_vendas.astype({
    'matricula_funcionario':'str',
    'codigo_produto':'str'
})

In [14]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   str
 1   nome_funcionario       3000 non-null   str
 2   cargo                  3000 non-null   str
 3   codigo_loja            3000 non-null   str
 4   nome_loja              3000 non-null   str
 5   codigo_produto         3000 non-null   str
 6   descricao_produto      3000 non-null   str
 7   categoria              3000 non-null   str
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    str
 12  dt_venda               3000 non-null   datetime64[us]
 13  dt_entrega             3000 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(2), int64(1), str(9)
memory usage: 536.2 KB

In [15]:
# caso não converta logo ao carregar o arquivo
df_vendas['dt_entrega'] = pd.to_datetime(df_vendas['dt_entrega'], format='%d/%m/%Y %H:%M')

In [16]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   str
 1   nome_funcionario       3000 non-null   str
 2   cargo                  3000 non-null   str
 3   codigo_loja            3000 non-null   str
 4   nome_loja              3000 non-null   str
 5   codigo_produto         3000 non-null   str
 6   descricao_produto      3000 non-null   str
 7   categoria              3000 non-null   str
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    str
 12  dt_venda               3000 non-null   datetime64[us]
 13  dt_entrega             3000 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(2), int64(1), str(9)
memory usage: 536.2 KB

In [17]:
df_vendas.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,"0,05",2019-08-14 16:56:00,2019-08-19 15:52:00

In [18]:
# quantidade total de produtos vendidos
df_vendas['quantidade'].sum()

np.int64(7360)

#Missing values/Valores faltantes

In [19]:
# caso queira completar valores nulos com 0
#df_vendas['comissao'] = df_vendas['comissao'].fillna(0)

In [20]:
# caso queira completar valores nulos com o último valor válido antes do valor nulo em questão
# df_vendas['comissao'] = df_vendas['comissao'].ffill()

In [ ]:
 # caso queira completar valores nulos com o primeiro valor válido depois do valor nulo em questão
df_vendas['comissao'] = df_vendas['comissao'].bfill()
df_vendas['comissao']

0       0,05
1       0,05
2       0,05
3       0,05
4       0,05
        ...
2995    0,09
2996    0,09
2997    0,09
2998    0,09
2999    0,09
Name: comissao, Length: 3000, dtype: str

In [22]:
# caso queira linhas com valores nulos removidas, independente da linha ter valores em outras colunas
# df_vendas.dropna(inplace=True)
# df_vendas.info()

In [23]:
df_vendas['comissao'] = df_vendas['comissao'].str.replace(',', '.')
df_vendas['comissao'] = df_vendas['comissao'].astype(float)

In [24]:
# moda das comissões
moda = df_vendas['comissao'].mode()[0]
print(moda)

0.05

In [25]:
# caso queira completar nulos com o valor da moda obtida
# df_vendas['comissao'] = df_vendas['comissao'].fillna(moda)

In [26]:
df_vendas['comissao']

0       0.05
1       0.05
2       0.05
3       0.05
4       0.05
        ...
2995    0.09
2996    0.09
2997    0.09
2998    0.09
2999    0.09
Name: comissao, Length: 3000, dtype: float64

In [27]:
# Exemplo de quartis de comissão (apenas exemplar de método, pois há muita inconsistência nas comissões originalmente)

# Criando nova coluna para os grupos onde:
# q=4 4 grupos (quartis)
# labels=False retorna apenas os números dos grupos (0, 1, 2, 3) em vez de intervalos
# duplicates='drop' resolve valores duplicados nos limites dos quartis, por isso foram criados apenas 3 grupos

df_vendas['comissao_qcut'] = pd.qcut(df_vendas['comissao'], q=4, labels=False, duplicates='drop')

# Moda por quartil

# Agrupa o dataframe pelos quartis de comissão criados anteriormente
# Para cada grupo, seleciona a coluna 'codigo_loja'
# .agg() aplica uma função personalizada de agregação calcula a moda (valor mais frequente) e pega o primeiro elemento, tratando os sem moda definida

mode_by_quartile = df_vendas.groupby('comissao_qcut')['codigo_loja'].agg(lambda x: x.mode()[0] if not x.mode().empty else 'No mode')


print("Moda de 'codigo_loja' por quartis de 'comissao':")
print(mode_by_quartile)

Moda de 'codigo_loja' por quartis de 'comissao':
comissao_qcut
0    CL002
1    CL001
2    CL003
Name: codigo_loja, dtype: str

In [28]:
print("\nDistribuição de registros por quartil:")
print(df_vendas['comissao_qcut'].value_counts().sort_index())

Distribuição de registros por quartil:
comissao_qcut
0    1610
1     789
2     601
Name: count, dtype: int64

In [29]:
display(df_vendas)

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega,comissao_qcut
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,0.05,2020-09-28 16:19:00,2020-10-05 16:31:00,0
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,0.05,2020-03-07 12:47:00,2020-03-08 12:47:00,0
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,0.05,2019-04-21 10:48:00,2019-04-23 15:55:00,0
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,0.05,2020-05-07 17:59:00,2020-05-08 14:31:00,0
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,88.9,189.9,3,0.09,2019-11-04 15:40:00,2019-11-05 10:40:00,1
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,59.9,142.4,3,0.09,2019-06-24 09:04:00,2019-06-24 10:50:00,1
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,3,0.09,2020-08-08 14:46:00,2020-08-09 14:07:00,1
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,0.09,2019-12-19 09:21:00,2019-12-19 10:51:00,1
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00,1

In [30]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   str
 1   nome_funcionario       3000 non-null   str
 2   cargo                  3000 non-null   str
 3   codigo_loja            3000 non-null   str
 4   nome_loja              3000 non-null   str
 5   codigo_produto         3000 non-null   str
 6   descricao_produto      3000 non-null   str
 7   categoria              3000 non-null   str
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               3000 non-null   float64
 12  dt_venda               3000 non-null   datetime64[us]
 13  dt_entrega             3000 non-null   datetime64[us]
 14  comissao_qcut          3000 non-null   int64
dtypes: datetime64[us](2), float64(3), int64(2), str(8)
memory usage: 558.7 KB