In [1]:
import pandas as pd
import plotly.express as px

## Importando dados

In [2]:
df_vendas = pd.read_csv('../data-scripts/5/Vendas.csv', parse_dates=['Data'])
df_vendas_dez = pd.read_excel('../data-scripts/5/Vendas - Dez.xlsx')
df_gerentes = pd.read_excel('../data-scripts/5/Gerentes.xlsx')

## Análise exploratória

In [3]:
df_vendas.info()
df_vendas.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 93910 entries, 0 to 93909
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   indice             93910 non-null  str
 1   Código Venda       92325 non-null  float64
 2   Data               92325 non-null  datetime64[us]
 3   ID Loja            92325 non-null  str
 4   Produto            92325 non-null  str
 5   Quantidade         92325 non-null  float64
 6   Valor Unitário     92325 non-null  str
 7   Valor Final        92182 non-null  float64
 8   Custo do Produto   92223 non-null  float64
dtypes: datetime64[us](1), float64(4), str(4)
memory usage: 11.1 MB

np.int64(0)

In [4]:
display(df_vendas)

,indice,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Custo do Produto
0,0,1.0,2023-01-01,Loja São Paulo 1,HD SSD Samsung 256 Gb,1.0,358R$,358.0,214.8
1,1,1.0,2023-01-01,Loja São Paulo 1,Kit Teclado e Mouse Sem Fio,2.0,180R$,360.0,216.0
2,2,1.0,2023-01-01,Loja São Paulo 1,HD SSD Kingston 500 Gb,1.0,368R$,368.0,220.8
3,3,2.0,2023-01-02,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,3.0,250R$,750.0,450.0
4,4,2.0,2023-01-02,Loja São Paulo 1,Cartucho de Tinta HP BK123,1.0,70R$,70.0,42.0
...,...,...,...,...,...,...,...,...,...
93905,93905,65012.0,2023-11-30,Loja Rio de Janeiro 2,Memória DDR 3 Seagate 8 Gb,2.0,270R$,NaN,324.0
93906,93906,65013.0,2023-11-30,Loja João Pessoa,Calculadora Cientifica HP,2.0,140R$,NaN,NaN
93907,93907,65013.0,2023-11-30,Loja João Pessoa,Mousepad Gamer,3.0,72R$,216.0,129.6
93908,93908,65014.0,2023-11-30,Loja Porto Alegre,Calculadora Cientifica HP,5.0,140R$,700.0,420.0
93909,93909,65014.0,2023-11-30,Loja Porto Alegre,Memória DDR 4 Seagate 4 Gb,4.0,250R$,1000.0,600.0

In [5]:
df_filtrado = df_vendas.loc[550:800]
df_filtrado

,indice,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Custo do Produto
550,550,381.0,2023-01-03,Loja Porto Alegre,Mouse com Fio Microsoft,2.0,50R$,100.0,60.0
551,551,382.0,2023-01-03,Loja João Pessoa,Fone de Ouvido Bluetooth HP,2.0,100R$,200.0,120.0
552,552,382.0,2023-01-03,Loja João Pessoa,HD SSD Seagate 750 Gb,1.0,706R$,706.0,423.6
553,553,383.0,2023-01-03,Loja Porto Alegre,Roteador 300 Mbps Tplink,2.0,190R$,380.0,228.0
554,554,384.0,2023-01-03,Loja Fortaleza,Memória DDR 4 Seagate 4 Gb,3.0,250R$,750.0,450.0
...,...,...,...,...,...,...,...,...,...
796,796,533.0,2023-01-04,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,2.0,250R$,500.0,300.0
797,"797,533,2023-01-04,Loja São Paulo 1,""Mouse sem...",NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
798,798,534.0,2023-01-04,Loja Rio de Janeiro 2,Mouse com Fio Microsoft,1.0,50R$,50.0,30.0
799,799,535.0,2023-01-04,Loja Campinas,Mouse Pad Colorido,2.0,25R$,50.0,30.0
800,800,536.0,2023-01-04,Loja Florianópolis,HD SSD Samsung 256 Gb,3.0,358R$,1074.0,644.4

In [6]:
df_vendas_dez.info()
print('')
df_vendas_dez.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 7089 entries, 0 to 7088
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Código Venda      7089 non-null   int64
 1   Data              7089 non-null   datetime64[us]
 2   ID Loja           7089 non-null   str
 3   Produto           7089 non-null   str
 4   Quantidade        7089 non-null   int64
 5   Valor Unitário    7089 non-null   int64
 6   Valor Final       7089 non-null   int64
 7   Custo do Produto  7089 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(4), str(2)
memory usage: 711.0 KB

np.int64(16)

In [7]:
display(df_vendas_dez)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Custo do Produto
0,65014,2023-12-01,Loja Porto Alegre,Kit Teclado e Mouse Sem Fio,5,114,570,342.0
1,65014,2023-12-01,Loja Porto Alegre,Mouse sem Fio Microsoft,1,269,269,161.4
2,65016,2023-12-01,Loja São Paulo 2,Mouse Pad Colorido,2,363,726,435.6
3,65016,2023-12-01,Loja São Paulo 2,Mouse sem Fio Microsoft,1,250,250,150.0
4,65017,2023-12-01,Loja Fortaleza,Teclado sem Fio Megaware,3,92,276,165.6
...,...,...,...,...,...,...,...,...
7084,69996,2023-12-26,Loja Rio de Janeiro 1,Mouse Pad Colorido,2,102,204,122.4
7085,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,4,270,1080,648.0
7086,69996,2023-12-26,Loja Rio de Janeiro 1,HD SSD Maxtel 750 Gb,1,87,87,52.2
7087,69997,2023-12-26,Loja João Pessoa,HD SSD Kingston 1 Tb,1,108,108,64.8
7088,69997,2023-12-26,Loja João Pessoa,Mouse Pad Colorido,2,133,266,159.6

In [8]:
df_vendas_dez.info()

<class 'pandas.DataFrame'>
RangeIndex: 7089 entries, 0 to 7088
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Código Venda      7089 non-null   int64
 1   Data              7089 non-null   datetime64[us]
 2   ID Loja           7089 non-null   str
 3   Produto           7089 non-null   str
 4   Quantidade        7089 non-null   int64
 5   Valor Unitário    7089 non-null   int64
 6   Valor Final       7089 non-null   int64
 7   Custo do Produto  7089 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(4), str(2)
memory usage: 711.0 KB

In [9]:
df_gerentes.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID Loja  14 non-null     str
 1   Gerente  14 non-null     str
dtypes: str(2)
memory usage: 657.0 bytes

In [10]:
display(df_gerentes)

                  ID Loja   Gerente
0        Loja São Paulo 1     Paulo
1        Loja São Paulo 2     Joana
2        Loja São Paulo 3     Maria
3           Loja Campinas   Letícia
4   Loja Rio de Janeiro 1     Fábio
5   Loja Rio de Janeiro 2     Luiza
6      Loja Florianópolis     Julia
7             Loja Recife    Nicole
8           Loja Blumenau     André
9          Loja Fortaleza      João
10       Loja João Pessoa    Marcus
11             Loja Natal    Amanda
12      Loja Porto Alegre     Carol
13           Loja Maringá  Andressa

## Tratamento de dados

In [11]:
colunas = df_vendas.columns
colunas_gerente = df_gerentes.columns
colunas_dez = df_vendas_dez.columns
print(colunas)
print(colunas_dez)
print(colunas_gerente)
# Padronizando as colunas
colunas = list(i.strip().replace(' ', '_').lower() for i in colunas)
colunas_dez = list(i.strip().replace(' ', '_').lower() for i in colunas_dez)
colunas_gerente = list(i.strip().replace(' ', '_').lower() for i in colunas_gerente)

Index(['indice', 'Código Venda', 'Data', 'ID Loja', 'Produto', 'Quantidade',
       'Valor Unitário', 'Valor Final', 'Custo do Produto '],
      dtype='str')
Index(['Código Venda', 'Data', 'ID Loja', 'Produto', 'Quantidade',
       'Valor Unitário', 'Valor Final', 'Custo do Produto'],
      dtype='str')
Index(['ID Loja', 'Gerente'], dtype='str')

In [12]:
#Aplicando
df_vendas.columns = colunas
df_vendas_dez.columns = colunas_dez
df_gerentes.columns = colunas_gerente
print(colunas)
print(colunas_dez)
print(colunas_gerente)

['indice', 'código_venda', 'data', 'id_loja', 'produto', 'quantidade', 'valor_unitário', 'valor_final', 'custo_do_produto']
['código_venda', 'data', 'id_loja', 'produto', 'quantidade', 'valor_unitário', 'valor_final', 'custo_do_produto']
['id_loja', 'gerente']

In [13]:
#Apagando a coluna índice
df_vendas = df_vendas.drop(columns=['indice'])

In [14]:
#Removendo linhas duplicadas
df_vendas.drop_duplicates(inplace=True)
df_vendas_dez.drop_duplicates(inplace=True)

In [15]:
df_vendas['valor_unitário'] = df_vendas['valor_unitário'].str.replace(r'R\$', '', regex=True)# Removido o R$
df_vendas['valor_unitário'] = df_vendas['valor_unitário'].astype(float)

In [16]:
df_vendas.fillna({'valor_final': df_vendas['quantidade']*df_vendas['valor_unitário']}, inplace=True) #Cálculo coluna valor_final
df_vendas.fillna({'custo_do_produto': df_vendas['valor_final']*.6}, inplace=True) #Cálculo coluna custo_do_produto
display(df_vendas)

,código_venda,data,id_loja,produto,quantidade,valor_unitário,valor_final,custo_do_produto
0,1.0,2023-01-01,Loja São Paulo 1,HD SSD Samsung 256 Gb,1.0,358.0,358.0,214.8
1,1.0,2023-01-01,Loja São Paulo 1,Kit Teclado e Mouse Sem Fio,2.0,180.0,360.0,216.0
2,1.0,2023-01-01,Loja São Paulo 1,HD SSD Kingston 500 Gb,1.0,368.0,368.0,220.8
3,2.0,2023-01-02,Loja São Paulo 1,Memória DDR 4 Seagate 4 Gb,3.0,250.0,750.0,450.0
4,2.0,2023-01-02,Loja São Paulo 1,Cartucho de Tinta HP BK123,1.0,70.0,70.0,42.0
...,...,...,...,...,...,...,...,...
93905,65012.0,2023-11-30,Loja Rio de Janeiro 2,Memória DDR 3 Seagate 8 Gb,2.0,270.0,540.0,324.0
93906,65013.0,2023-11-30,Loja João Pessoa,Calculadora Cientifica HP,2.0,140.0,280.0,168.0
93907,65013.0,2023-11-30,Loja João Pessoa,Mousepad Gamer,3.0,72.0,216.0,129.6
93908,65014.0,2023-11-30,Loja Porto Alegre,Calculadora Cientifica HP,5.0,140.0,700.0,420.0
93909,65014.0,2023-11-30,Loja Porto Alegre,Memória DDR 4 Seagate 4 Gb,4.0,250.0,1000.0,600.0

In [17]:
df_vendas.dropna(inplace=True)
df_vendas.isna().sum()

código_venda        0
data                0
id_loja             0
produto             0
quantidade          0
valor_unitário      0
valor_final         0
custo_do_produto    0
dtype: int64

In [18]:
df_faturamento_total_base = df_vendas['valor_final'].sum()
print(f'Faturamento df_vendas: R${df_faturamento_total_base:,.2f}')

Faturamento df_vendas: R$42,022,673.00

In [19]:
df_faturamento_total_dez = df_vendas_dez['valor_final'].sum()
print(f'Faturamento df_vendas_dez: R${df_faturamento_total_dez:,.2f}')

Faturamento df_vendas_dez: R$2,912,843.00

## Concat

In [20]:
df_vendas_final = pd.concat([df_vendas, df_vendas_dez], axis=0, join='inner')

## Merge

In [21]:
df_vendas_final = df_vendas_final.merge(df_gerentes, on='id_loja', how='outer')

In [22]:
df_vendas_final.head(-1)

,código_venda,data,id_loja,produto,quantidade,valor_unitário,valor_final,custo_do_produto,gerente
0,47.0,2023-01-02,Loja Blumenau,Roteador 300 Mbps Tplink,1.0,190.0,190.0,114.0,André
1,59.0,2023-01-02,Loja Blumenau,Teclado sem Fio Microsoft,2.0,170.0,340.0,204.0,André
2,66.0,2023-01-02,Loja Blumenau,Memória DDR 4 Seagate 4 Gb,4.0,250.0,1000.0,600.0,André
3,66.0,2023-01-02,Loja Blumenau,Memória DDR 4 Seagate 4 Gb,1.0,250.0,250.0,150.0,André
4,94.0,2023-01-02,Loja Blumenau,Memória DDR 4 Seagate 4 Gb,4.0,250.0,1000.0,600.0,André
...,...,...,...,...,...,...,...,...,...
98245,69971.0,2023-12-26,Loja São Paulo 3,Teclado Gamer com Led,2.0,209.0,418.0,250.8,Maria
98246,69971.0,2023-12-26,Loja São Paulo 3,Calculadora Cientifica HP,2.0,163.0,326.0,195.6,Maria
98247,69975.0,2023-12-26,Loja São Paulo 3,Teclado sem Fio Multi,5.0,66.0,330.0,198.0,Maria
98248,69975.0,2023-12-26,Loja São Paulo 3,Calculadora Cientifica HP,1.0,155.0,155.0,93.0,Maria
98249,69982.0,2023-12-26,Loja São Paulo 3,HD SSD Maxtel 750 Gb,2.0,311.0,622.0,373.2,Maria

## Tratamento de dados

In [23]:
df_vendas_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 98251 entries, 0 to 98250
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   código_venda      98251 non-null  float64
 1   data              98251 non-null  datetime64[us]
 2   id_loja           98251 non-null  str
 3   produto           98251 non-null  str
 4   quantidade        98251 non-null  float64
 5   valor_unitário    98251 non-null  float64
 6   valor_final       98251 non-null  float64
 7   custo_do_produto  98251 non-null  float64
 8   gerente           98251 non-null  str
dtypes: datetime64[us](1), float64(5), str(3)
memory usage: 11.1 MB

In [24]:
#df_vendas_final['quantidade'] = df_vendas_final['quantidade'].astype(int)
display(df_vendas_final)

,código_venda,data,id_loja,produto,quantidade,valor_unitário,valor_final,custo_do_produto,gerente
0,47.0,2023-01-02,Loja Blumenau,Roteador 300 Mbps Tplink,1.0,190.0,190.0,114.0,André
1,59.0,2023-01-02,Loja Blumenau,Teclado sem Fio Microsoft,2.0,170.0,340.0,204.0,André
2,66.0,2023-01-02,Loja Blumenau,Memória DDR 4 Seagate 4 Gb,4.0,250.0,1000.0,600.0,André
3,66.0,2023-01-02,Loja Blumenau,Memória DDR 4 Seagate 4 Gb,1.0,250.0,250.0,150.0,André
4,94.0,2023-01-02,Loja Blumenau,Memória DDR 4 Seagate 4 Gb,4.0,250.0,1000.0,600.0,André
...,...,...,...,...,...,...,...,...,...
98246,69971.0,2023-12-26,Loja São Paulo 3,Calculadora Cientifica HP,2.0,163.0,326.0,195.6,Maria
98247,69975.0,2023-12-26,Loja São Paulo 3,Teclado sem Fio Multi,5.0,66.0,330.0,198.0,Maria
98248,69975.0,2023-12-26,Loja São Paulo 3,Calculadora Cientifica HP,1.0,155.0,155.0,93.0,Maria
98249,69982.0,2023-12-26,Loja São Paulo 3,HD SSD Maxtel 750 Gb,2.0,311.0,622.0,373.2,Maria
98250,69994.0,2023-12-26,Loja São Paulo 3,Fone de Ouvido Bluetooth HP,1.0,170.0,170.0,102.0,Maria

In [25]:
df_vendas_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 98251 entries, 0 to 98250
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   código_venda      98251 non-null  float64
 1   data              98251 non-null  datetime64[us]
 2   id_loja           98251 non-null  str
 3   produto           98251 non-null  str
 4   quantidade        98251 non-null  float64
 5   valor_unitário    98251 non-null  float64
 6   valor_final       98251 non-null  float64
 7   custo_do_produto  98251 non-null  float64
 8   gerente           98251 non-null  str
dtypes: datetime64[us](1), float64(5), str(3)
memory usage: 11.1 MB

## Perguntas de negócio

In [26]:
filtro1 = df_vendas_final

In [27]:
display(df_vendas_final)
df_vendas_final.isna().sum()

,código_venda,data,id_loja,produto,quantidade,valor_unitário,valor_final,custo_do_produto,gerente
0,47.0,2023-01-02,Loja Blumenau,Roteador 300 Mbps Tplink,1.0,190.0,190.0,114.0,André
1,59.0,2023-01-02,Loja Blumenau,Teclado sem Fio Microsoft,2.0,170.0,340.0,204.0,André
2,66.0,2023-01-02,Loja Blumenau,Memória DDR 4 Seagate 4 Gb,4.0,250.0,1000.0,600.0,André
3,66.0,2023-01-02,Loja Blumenau,Memória DDR 4 Seagate 4 Gb,1.0,250.0,250.0,150.0,André
4,94.0,2023-01-02,Loja Blumenau,Memória DDR 4 Seagate 4 Gb,4.0,250.0,1000.0,600.0,André
...,...,...,...,...,...,...,...,...,...
98246,69971.0,2023-12-26,Loja São Paulo 3,Calculadora Cientifica HP,2.0,163.0,326.0,195.6,Maria
98247,69975.0,2023-12-26,Loja São Paulo 3,Teclado sem Fio Multi,5.0,66.0,330.0,198.0,Maria
98248,69975.0,2023-12-26,Loja São Paulo 3,Calculadora Cientifica HP,1.0,155.0,155.0,93.0,Maria
98249,69982.0,2023-12-26,Loja São Paulo 3,HD SSD Maxtel 750 Gb,2.0,311.0,622.0,373.2,Maria
98250,69994.0,2023-12-26,Loja São Paulo 3,Fone de Ouvido Bluetooth HP,1.0,170.0,170.0,102.0,Maria

código_venda        0
data                0
id_loja             0
produto             0
quantidade          0
valor_unitário      0
valor_final         0
custo_do_produto    0
gerente             0
dtype: int64

### Qual foi o faturamento total no período analisado?

In [28]:
df_faturamento_total = df_vendas_final['valor_final'].sum()
print(f'Faturamento total: R${df_faturamento_total:,.2f}')

Faturamento total: R$44,935,516.00

### Qual loja teve o maior faturamento?

In [29]:
maior_fat_loja = df_vendas_final.groupby('id_loja')['valor_final'].sum().reset_index().sort_values(by='valor_final', ascending=False)


fig = px.bar(maior_fat_loja, x='id_loja', y='valor_final', text=maior_fat_loja['valor_final'], title='Receita por Loja', color='id_loja')

fig.update_traces(textposition='outside', texttemplate='R$ %{text:0.3s}')

fig.show()

### Qual produto foi o mais vendido em quantidade?

In [30]:
maior_prod_vend = df_vendas_final.groupby('produto')['quantidade'].sum().reset_index().sort_values(by='quantidade', ascending=False)


fig = px.bar(maior_prod_vend, x='produto', y='quantidade', title='Quantidade de produtos vendidos', color_discrete_sequence=px.colors.qualitative.Bold)

fig.update_traces(textposition='outside', texttemplate='R$ %{text:0.3s}')

fig.show()

### Qual produto foi o menos vendido em quantidade?

In [31]:
menor_prod_vend = df_vendas_final.groupby('produto')['quantidade'].sum().reset_index().sort_values(by='quantidade', ascending=True)


fig = px.bar(menor_prod_vend, x='produto', y='quantidade', title='Quantidade de produtos vendidos', color_discrete_sequence=px.colors.qualitative.Bold)

fig.update_traces(textposition='outside', texttemplate='R$ %{text:0.3s}')

fig.show()

### Qual produto gerou a maior receita (somatório do Valor Final)?

In [32]:
maior_prod_receita = df_vendas_final.groupby('produto')['valor_final'].sum().reset_index().sort_values(by='valor_final', ascending=False)

fig = px.bar(maior_prod_receita, x='produto', y='valor_final', text='valor_final', title='Produtos e suas receitas', color_discrete_sequence=px.colors.qualitative.Bold)

fig.update_traces(textposition='outside', texttemplate='R$ %{text:0.3s}')

fig.show()

### Qual produto gerou maior lucro?

In [33]:
df_vendas_final['lucro'] = df_vendas_final['valor_final'] - df_vendas_final['custo_do_produto']
maior_prod_lucro = df_vendas_final.groupby('produto')['lucro'].sum().reset_index().sort_values(by='lucro', ascending=False)


fig = px.bar(maior_prod_lucro, x='produto', y='lucro', text='lucro', title='Produtos e seus lucros', color_discrete_sequence=px.colors.qualitative.Bold)

fig.update_traces(textposition='outside', texttemplate='R$ %{text:0.3s}')

fig.show()

### Qual a média da margem de lucro por produto?

In [34]:
df_vendas_final['margem_lucro'] = (df_vendas_final['valor_final'] - df_vendas_final['custo_do_produto']) / df_vendas_final['valor_final']

media_lucro_prod = df_vendas_final.groupby('produto')['margem_lucro'].mean().reset_index().sort_values(by='margem_lucro', ascending=False)


fig = px.bar(media_lucro_prod, x='produto', y='margem_lucro', text='margem_lucro', title='Produtos e suas margens de lucro', color_discrete_sequence=px.colors.qualitative.Bold)

fig.update_traces(textposition='outside', texttemplate='%{text:0.1}')

fig.show()

## Análise Gerencial

### Qual gerente obteve maior números de vendas (Quantidade)?

In [35]:
df_vendas_gerente = df_vendas_final['gerente'].value_counts().reset_index().sort_values(by='count', ascending=False)

display(df_vendas_gerente)

     gerente  count
0      Maria  15379
1      Paulo  11939
2      Luiza  11926
3      Joana  11799
4      Fábio  11582
5      André   4091
6     Nicole   4004
7    Letícia   3996
8       João   3963
9     Marcus   3944
10     Julia   3943
11  Andressa   3936
12    Amanda   3886
13     Carol   3863

### Qual gerente gerou maior receita?

In [36]:
df_qtd_gerente = df_vendas_final.groupby('gerente')['valor_final'].sum().reset_index().sort_values(by='valor_final',ascending=False)

display(df_qtd_gerente)

     gerente  valor_final
11     Maria    7042342.0
13     Paulo    5467970.0
9      Luiza    5444245.0
5      Joana    5421778.0
4      Fábio    5260806.0
12    Nicole    1858957.0
2      André    1853073.0
8    Letícia    1848362.0
6       João    1841223.0
10    Marcus    1840447.0
7      Julia    1799010.0
0     Amanda    1792532.0
1   Andressa    1759270.0
3      Carol    1705501.0

### Qual gerente gerou o maior lucro?

In [37]:
df_lucro_gerente = df_vendas_final.groupby('gerente')['lucro'].sum().reset_index().sort_values(by='lucro',ascending=False)

display(df_lucro_gerente)

     gerente      lucro
11     Maria  2816936.8
13     Paulo  2187188.0
9      Luiza  2177698.0
5      Joana  2168711.2
4      Fábio  2104322.4
12    Nicole   743582.8
2      André   741235.2
8    Letícia   739362.8
6       João   736507.2
10    Marcus   736178.8
7      Julia   719604.0
0     Amanda   717012.8
1   Andressa   703708.0
3      Carol   682200.4

### Qual foi o mês com maior faturamento?

In [38]:
df_vendas_final['ano - mes'] = df_vendas_final['data'].dt.to_period('M')

In [39]:
df_fat_mes = df_vendas_final.groupby('ano - mes')['valor_final'].sum().reset_index()

df_fat_mes['ano - mes'] = df_fat_mes['ano - mes'].dt.to_timestamp()
fig = px.line(df_fat_mes, x='ano - mes', y='valor_final')

fig.show()

In [40]:
df_vendas_final['mes'] = df_vendas_final['data'].dt.month

In [41]:
df_gerentes_mes = df_vendas_final.groupby(['gerente', 'mes'])['valor_final'].sum().reset_index()

fig = px.line(
    df_gerentes_mes,
    x='mes',
    y='valor_final',
    color='gerente',
    title='Vendas Mensais por Gerente',
    height=500,
    width=1000,
    markers=True
)

fig.update_yaxes(title='Vendas', ticks='outside', tickprefix='R$ ')

fig.show()

### Quais foram os produtos mais vendidos por cada gerente?

In [42]:
df_prod_gerente = df_vendas_final.groupby(['gerente', 'produto'])['quantidade'].sum().reset_index().sort_values(by='quantidade',ascending=False)



fig = px.treemap(df_prod_gerente, path=[px.Constant('Gerentes'), 'gerente', 'produto'], values='quantidade')

fig.show()